<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert([

            [
                "name"=>"مدينة الكويت",
                "slug"=>"مدينة-الكويت",
                "active"=>"1",
                "created_at"=>Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"=>Carbon::now()->format('Y-m-d H:i:s')
            ],
            ["name"=>"دسمان","slug"=>"دسمان","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الشرق","slug"=>"الشرق","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الصوابر","slug"=>"الصوابر","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"المرقاب","slug"=>"المرقاب","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"القبلة","slug"=>"القبلة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الصالحية","slug"=>"الصالحية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الوطية","slug"=>"الوطية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"بنيد القار","slug"=>"بنيد-القار","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"كيفان","slug"=>"كيفان","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الدوحة","slug"=>"الدوحة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الدسمة","slug"=>"الدسمة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الدعية","slug"=>"الدعية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"المنصورية","slug"=>"المنصورية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ضاحية عبد الله السالم","slug"=>"ضاحية-عبد-الله-السالم","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"النزهة","slug"=>"النزهة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الفيحاء","slug"=>"الفيحاء","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الشامية","slug"=>"الشامية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الروضة","slug"=>"الروضة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"العديلية","slug"=>"العديلية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الخالدية","slug"=>"الخالدية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"القادسية","slug"=>"القادسية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"قرطبة","slug"=>"قرطبة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"السرة","slug"=>"السرة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"اليرموك","slug"=>"اليرموك","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الشويخ","slug"=>"الشويخ","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الري","slug"=>"الري","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"غرناطة","slug"=>"غرناطة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الصليبيخات والدوحة","slug"=>"الصليبيخات-والدوحة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"النهضة","slug"=>"النهضة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"مدينة جابر الأحمد","slug"=>"مدينة-جابر-الأحمد","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"القيروان","slug"=>"القيروان","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"شمال غرب الصليبيخات","slug"=>"شمال-غرب-الصليبيخات","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جزيرة فيلكا","slug"=>"جزيرة-فيلكا","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جزيرة كبر","slug"=>"جزيرة-كبر","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جزيرة عوهة","slug"=>"جزيرة-عوهة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جزيرة أم المرادم","slug"=>"جزيرة-أم-المرادم","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جزيرة مسكان","slug"=>"جزيرة-مسكان","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جزيرة قاروه","slug"=>"جزيرة-قاروه","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جزيرة أم النمل","slug"=>"جزيرة-أم-النمل","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جزيرة الشويخ","slug"=>"جزيرة-الشويخ","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الفنطاس","slug"=>"الفنطاس","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"العقيلة","slug"=>"العقيلة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الظهر","slug"=>"الظهر","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"المقوع","slug"=>"المقوع","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"المهبولة","slug"=>"المهبولة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الرقة","slug"=>"الرقة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"هدية","slug"=>"هدية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"أبو حليفة","slug"=>"أبو-حليفة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الصباحية","slug"=>"الصباحية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"المنقف","slug"=>"المنقف","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الفحيحيل","slug"=>"الفحيحيل","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الأحمدي","slug"=>"الأحمدي","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الوفرة","slug"=>"الوفرة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الزور","slug"=>"الزور","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الخيران","slug"=>"الخيران","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ميناء عبد الله","slug"=>"ميناء-عبد-الله","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الوفرة الزراعية","slug"=>"الوفرة-الزراعية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"بنيدر","slug"=>"بنيدر","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الجليعة","slug"=>"الجليعة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الضباعية","slug"=>"الضباعية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ضاحية جابر العلي","slug"=>"ضاحية-جابر-العلي","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ضاحية فهد الأحمد","slug"=>"ضاحية-فهد-الأحمد","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الشعيبة","slug"=>"الشعيبة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"واره","slug"=>"واره","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"مدينة صباح الأحمد","slug"=>"مدينة-صباح-الأحمد","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"النويصيب","slug"=>"النويصيب","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"مدينة الخيران","slug"=>"مدينة-الخيران","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ضاحية علي صباح السالم","slug"=>"ضاحية-علي-صباح-السالم","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"مدينة صباح الأحمد البحرية","slug"=>"مدينة-صباح-الأحمد-البحرية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"أبرق خيطان","slug"=>"أبرق-خيطان","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الأندلس","slug"=>"الأندلس","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"اشبيلية","slug"=>"اشبيلية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جليب الشيوخ","slug"=>"جليب-الشيوخ","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"خيطان","slug"=>"خيطان","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"خيطان الجديدة","slug"=>"خيطان-الجديدة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"العمرية","slug"=>"العمرية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"العارضية","slug"=>"العارضية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"العارضية الصناعية","slug"=>"العارضية-الصناعية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"العباسية","slug"=>"العباسية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الفردوس","slug"=>"الفردوس","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الفروانية","slug"=>"الفروانية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الحساوي","slug"=>"الحساوي","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الشدادية","slug"=>"الشدادية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الرابية","slug"=>"الرابية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الرحاب","slug"=>"الرحاب","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الرقعي","slug"=>"الرقعي","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الري الصناعية","slug"=>"الري-الصناعية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ضاحية صباح الناصر","slug"=>"ضاحية-صباح-الناصر","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ضاحية عبد الله المبارك","slug"=>"ضاحية-عبد-الله-المبارك","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الضجيج","slug"=>"الضجيج","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الصليبية","slug"=>"الصليبية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"أمغرة","slug"=>"أمغرة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"النعيم","slug"=>"النعيم","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"القصر","slug"=>"القصر","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الواحة","slug"=>"الواحة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"تيماء","slug"=>"تيماء","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"النسيم","slug"=>"النسيم","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"العيون","slug"=>"العيون","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"القيصرية","slug"=>"القيصرية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"العبدلي","slug"=>"العبدلي","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الجهراء القديمة","slug"=>"الجهراء-القديمة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الجهراء الجديدة","slug"=>"الجهراء-الجديدة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"كاظمة","slug"=>"كاظمة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"مدينة سعد العبد الله","slug"=>"مدينة-سعد-العبد-الله","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"السالمي","slug"=>"السالمي","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"المطلاع","slug"=>"المطلاع","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"مدينة الحرير","slug"=>"مدينة-الحرير","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الروضتين","slug"=>"الروضتين","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"كبد","slug"=>"كبد","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الصبية","slug"=>"الصبية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جزيرة بوبيان","slug"=>"جزيرة-بوبيان","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جزيرة وربة","slug"=>"جزيرة-وربة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الجهراء","slug"=>"الجهراء","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"حولي","slug"=>"حولي","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الشعب","slug"=>"الشعب","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"السالمية","slug"=>"السالمية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الرميثية","slug"=>"الرميثية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الجابرية","slug"=>"الجابرية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"مشرف","slug"=>"مشرف","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"بيان","slug"=>"بيان","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"آلبدع","slug"=>"آلبدع","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"النقرة","slug"=>"النقرة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ميدان حولي","slug"=>"ميدان-حولي","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ضاحية مبارك العبد الله الجابر","slug"=>"ضاحية-مبارك-العبد-الله-الجابر","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"سلوى","slug"=>"سلوى","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"جنوب السرة","slug"=>"جنوب-السرة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الزهراء","slug"=>"الزهراء","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الصديق","slug"=>"الصديق","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"حطين","slug"=>"حطين","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"السلام","slug"=>"السلام","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الشهداء","slug"=>"الشهداء","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"العدان","slug"=>"العدان","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"القصور","slug"=>"القصور","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"القرين","slug"=>"القرين","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ضاحية صباح السالم","slug"=>"ضاحية-صباح-السالم","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"المسيلة","slug"=>"المسيلة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"المسايل","slug"=>"المسايل","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"أبو فطيرة","slug"=>"أبو-فطيرة","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"أبو الحصانية","slug"=>"أبو-الحصانية","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"صبحان","slug"=>"صبحان","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"الفنيطيس","slug"=>"الفنيطيس","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')],
            ["name"=>"ضاحية مبارك الكبير","slug"=>"ضاحية-مبارك-الكبير","active"=>"1","created_at"=>Carbon::now()->format('Y-m-d H:i:s'),"updated_at"=>Carbon::now()->format('Y-m-d H:i:s')]
        ]);
    }
}
